	IoTOctopus_QSYS u0 (
		.hps_io_hps_io_emac0_inst_TX_CLK (<connected-to-hps_io_hps_io_emac0_inst_TX_CLK>), // hps_io.hps_io_emac0_inst_TX_CLK
		.hps_io_hps_io_emac0_inst_TXD0   (<connected-to-hps_io_hps_io_emac0_inst_TXD0>),   //       .hps_io_emac0_inst_TXD0
		.hps_io_hps_io_emac0_inst_TXD1   (<connected-to-hps_io_hps_io_emac0_inst_TXD1>),   //       .hps_io_emac0_inst_TXD1
		.hps_io_hps_io_emac0_inst_TXD2   (<connected-to-hps_io_hps_io_emac0_inst_TXD2>),   //       .hps_io_emac0_inst_TXD2
		.hps_io_hps_io_emac0_inst_TXD3   (<connected-to-hps_io_hps_io_emac0_inst_TXD3>),   //       .hps_io_emac0_inst_TXD3
		.hps_io_hps_io_emac0_inst_RXD0   (<connected-to-hps_io_hps_io_emac0_inst_RXD0>),   //       .hps_io_emac0_inst_RXD0
		.hps_io_hps_io_emac0_inst_MDIO   (<connected-to-hps_io_hps_io_emac0_inst_MDIO>),   //       .hps_io_emac0_inst_MDIO
		.hps_io_hps_io_emac0_inst_MDC    (<connected-to-hps_io_hps_io_emac0_inst_MDC>),    //       .hps_io_emac0_inst_MDC
		.hps_io_hps_io_emac0_inst_RX_CTL (<connected-to-hps_io_hps_io_emac0_inst_RX_CTL>), //       .hps_io_emac0_inst_RX_CTL
		.hps_io_hps_io_emac0_inst_TX_CTL (<connected-to-hps_io_hps_io_emac0_inst_TX_CTL>), //       .hps_io_emac0_inst_TX_CTL
		.hps_io_hps_io_emac0_inst_RX_CLK (<connected-to-hps_io_hps_io_emac0_inst_RX_CLK>), //       .hps_io_emac0_inst_RX_CLK
		.hps_io_hps_io_emac0_inst_RXD1   (<connected-to-hps_io_hps_io_emac0_inst_RXD1>),   //       .hps_io_emac0_inst_RXD1
		.hps_io_hps_io_emac0_inst_RXD2   (<connected-to-hps_io_hps_io_emac0_inst_RXD2>),   //       .hps_io_emac0_inst_RXD2
		.hps_io_hps_io_emac0_inst_RXD3   (<connected-to-hps_io_hps_io_emac0_inst_RXD3>),   //       .hps_io_emac0_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),     //       .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_io_hps_io_sdio_inst_D0>),      //       .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_io_hps_io_sdio_inst_D1>),      //       .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),     //       .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_io_hps_io_sdio_inst_D2>),      //       .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_io_hps_io_sdio_inst_D3>),      //       .hps_io_sdio_inst_D3
		.hps_io_hps_io_spim0_inst_CLK    (<connected-to-hps_io_hps_io_spim0_inst_CLK>),    //       .hps_io_spim0_inst_CLK
		.hps_io_hps_io_spim0_inst_MOSI   (<connected-to-hps_io_hps_io_spim0_inst_MOSI>),   //       .hps_io_spim0_inst_MOSI
		.hps_io_hps_io_spim0_inst_MISO   (<connected-to-hps_io_hps_io_spim0_inst_MISO>),   //       .hps_io_spim0_inst_MISO
		.hps_io_hps_io_spim0_inst_SS0    (<connected-to-hps_io_hps_io_spim0_inst_SS0>),    //       .hps_io_spim0_inst_SS0
		.hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_io_hps_io_uart0_inst_RX>),     //       .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_io_hps_io_uart0_inst_TX>),     //       .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),     //       .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),     //       .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),     //       .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),     //       .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_can0_inst_RX      (<connected-to-hps_io_hps_io_can0_inst_RX>),      //       .hps_io_can0_inst_RX
		.hps_io_hps_io_can0_inst_TX      (<connected-to-hps_io_hps_io_can0_inst_TX>),      //       .hps_io_can0_inst_TX
		.hps_io_hps_io_can1_inst_RX      (<connected-to-hps_io_hps_io_can1_inst_RX>),      //       .hps_io_can1_inst_RX
		.hps_io_hps_io_can1_inst_TX      (<connected-to-hps_io_hps_io_can1_inst_TX>),      //       .hps_io_can1_inst_TX
		.hps_io_hps_io_gpio_inst_GPIO14  (<connected-to-hps_io_hps_io_gpio_inst_GPIO14>),  //       .hps_io_gpio_inst_GPIO14
		.hps_io_hps_io_gpio_inst_GPIO15  (<connected-to-hps_io_hps_io_gpio_inst_GPIO15>),  //       .hps_io_gpio_inst_GPIO15
		.hps_io_hps_io_gpio_inst_GPIO16  (<connected-to-hps_io_hps_io_gpio_inst_GPIO16>),  //       .hps_io_gpio_inst_GPIO16
		.hps_io_hps_io_gpio_inst_GPIO17  (<connected-to-hps_io_hps_io_gpio_inst_GPIO17>),  //       .hps_io_gpio_inst_GPIO17
		.hps_io_hps_io_gpio_inst_GPIO18  (<connected-to-hps_io_hps_io_gpio_inst_GPIO18>),  //       .hps_io_gpio_inst_GPIO18
		.hps_io_hps_io_gpio_inst_GPIO19  (<connected-to-hps_io_hps_io_gpio_inst_GPIO19>),  //       .hps_io_gpio_inst_GPIO19
		.hps_io_hps_io_gpio_inst_GPIO22  (<connected-to-hps_io_hps_io_gpio_inst_GPIO22>),  //       .hps_io_gpio_inst_GPIO22
		.hps_io_hps_io_gpio_inst_GPIO23  (<connected-to-hps_io_hps_io_gpio_inst_GPIO23>),  //       .hps_io_gpio_inst_GPIO23
		.hps_io_hps_io_gpio_inst_GPIO24  (<connected-to-hps_io_hps_io_gpio_inst_GPIO24>),  //       .hps_io_gpio_inst_GPIO24
		.hps_io_hps_io_gpio_inst_GPIO25  (<connected-to-hps_io_hps_io_gpio_inst_GPIO25>),  //       .hps_io_gpio_inst_GPIO25
		.hps_io_hps_io_gpio_inst_GPIO26  (<connected-to-hps_io_hps_io_gpio_inst_GPIO26>),  //       .hps_io_gpio_inst_GPIO26
		.hps_io_hps_io_gpio_inst_GPIO27  (<connected-to-hps_io_hps_io_gpio_inst_GPIO27>),  //       .hps_io_gpio_inst_GPIO27
		.hps_io_hps_io_gpio_inst_GPIO28  (<connected-to-hps_io_hps_io_gpio_inst_GPIO28>),  //       .hps_io_gpio_inst_GPIO28
		.hps_io_hps_io_gpio_inst_GPIO29  (<connected-to-hps_io_hps_io_gpio_inst_GPIO29>),  //       .hps_io_gpio_inst_GPIO29
		.hps_io_hps_io_gpio_inst_GPIO30  (<connected-to-hps_io_hps_io_gpio_inst_GPIO30>),  //       .hps_io_gpio_inst_GPIO30
		.hps_io_hps_io_gpio_inst_GPIO31  (<connected-to-hps_io_hps_io_gpio_inst_GPIO31>),  //       .hps_io_gpio_inst_GPIO31
		.hps_io_hps_io_gpio_inst_GPIO32  (<connected-to-hps_io_hps_io_gpio_inst_GPIO32>),  //       .hps_io_gpio_inst_GPIO32
		.hps_io_hps_io_gpio_inst_GPIO33  (<connected-to-hps_io_hps_io_gpio_inst_GPIO33>),  //       .hps_io_gpio_inst_GPIO33
		.hps_io_hps_io_gpio_inst_GPIO34  (<connected-to-hps_io_hps_io_gpio_inst_GPIO34>),  //       .hps_io_gpio_inst_GPIO34
		.hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),  //       .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO37  (<connected-to-hps_io_hps_io_gpio_inst_GPIO37>),  //       .hps_io_gpio_inst_GPIO37
		.hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),  //       .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO41  (<connected-to-hps_io_hps_io_gpio_inst_GPIO41>),  //       .hps_io_gpio_inst_GPIO41
		.hps_io_hps_io_gpio_inst_GPIO42  (<connected-to-hps_io_hps_io_gpio_inst_GPIO42>),  //       .hps_io_gpio_inst_GPIO42
		.hps_io_hps_io_gpio_inst_GPIO43  (<connected-to-hps_io_hps_io_gpio_inst_GPIO43>),  //       .hps_io_gpio_inst_GPIO43
		.hps_io_hps_io_gpio_inst_GPIO44  (<connected-to-hps_io_hps_io_gpio_inst_GPIO44>),  //       .hps_io_gpio_inst_GPIO44
		.hps_io_hps_io_gpio_inst_GPIO48  (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),  //       .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO49  (<connected-to-hps_io_hps_io_gpio_inst_GPIO49>),  //       .hps_io_gpio_inst_GPIO49
		.hps_io_hps_io_gpio_inst_GPIO50  (<connected-to-hps_io_hps_io_gpio_inst_GPIO50>),  //       .hps_io_gpio_inst_GPIO50
		.hps_io_hps_io_gpio_inst_GPIO55  (<connected-to-hps_io_hps_io_gpio_inst_GPIO55>),  //       .hps_io_gpio_inst_GPIO55
		.hps_io_hps_io_gpio_inst_GPIO56  (<connected-to-hps_io_hps_io_gpio_inst_GPIO56>),  //       .hps_io_gpio_inst_GPIO56
		.memory_mem_a                    (<connected-to-memory_mem_a>),                    // memory.mem_a
		.memory_mem_ba                   (<connected-to-memory_mem_ba>),                   //       .mem_ba
		.memory_mem_ck                   (<connected-to-memory_mem_ck>),                   //       .mem_ck
		.memory_mem_ck_n                 (<connected-to-memory_mem_ck_n>),                 //       .mem_ck_n
		.memory_mem_cke                  (<connected-to-memory_mem_cke>),                  //       .mem_cke
		.memory_mem_cs_n                 (<connected-to-memory_mem_cs_n>),                 //       .mem_cs_n
		.memory_mem_ras_n                (<connected-to-memory_mem_ras_n>),                //       .mem_ras_n
		.memory_mem_cas_n                (<connected-to-memory_mem_cas_n>),                //       .mem_cas_n
		.memory_mem_we_n                 (<connected-to-memory_mem_we_n>),                 //       .mem_we_n
		.memory_mem_reset_n              (<connected-to-memory_mem_reset_n>),              //       .mem_reset_n
		.memory_mem_dq                   (<connected-to-memory_mem_dq>),                   //       .mem_dq
		.memory_mem_dqs                  (<connected-to-memory_mem_dqs>),                  //       .mem_dqs
		.memory_mem_dqs_n                (<connected-to-memory_mem_dqs_n>),                //       .mem_dqs_n
		.memory_mem_odt                  (<connected-to-memory_mem_odt>),                  //       .mem_odt
		.memory_mem_dm                   (<connected-to-memory_mem_dm>),                   //       .mem_dm
		.memory_oct_rzqin                (<connected-to-memory_oct_rzqin>)                 //       .oct_rzqin
	);

